### ISSUE TITLE
v1.1.0 type definition file is in the wrong place

### ISSUE THREAD

**Issue by C-Higgins** [nobrainr/axios-morphism#23]
In v1.1.0 the `axios-morphism.d.ts` file moved from `dist/` to `dist/types/`, breaking types. Typescript won't pick up the file when it is located there.

**Comment by emyann** [comment]
hmmfrr, sorry about that 😞 I just sent a new release fixing that https://github.com/nobrainr/axios-morphism/pull/24#issuecomment-556335315 (here's a [live test](https://repl.it/@yrnd1/WindingMulticoloredClosedsource)).
Also This is version `1.3.1` and `morphism` is now a peer dependency.

**Comment by emyann** [comment]
Closing this as version `1.3.1` fixes the issue
